"""
RiskRegister - analysis & reporting.

Produces the artefacts a risk/governance team would actually use:
  1. A 5x5 inherent-risk heat map (count of risks per likelihood x impact cell)
  2. Residual vs inherent risk by category (does our control environment work?)
  3. A control-effectiveness summary
  4. A governance exceptions list: high residual risks + overdue reviews

Outputs:
  outputs/heatmap.png
  outputs/residual_by_category.png
  outputs/governance_report.md
"""

from __future__ import annotations
from pathlib import Path
import sqlite3
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

BASE = Path(__file__).parent
OUT = BASE / "outputs"
DB = BASE / "data" / "risks.db"

HIGH_RESIDUAL_THRESHOLD = 12   # residual score >= 12 treated as high/extreme


def load() -> pd.DataFrame:
    con = sqlite3.connect(DB)
    df = pd.read_sql("SELECT * FROM risks", con)
    con.close()
    return df


def heatmap(df: pd.DataFrame) -> None:
    grid = np.zeros((5, 5), dtype=int)
    for _, r in df.iterrows():
        grid[5 - r["impact"], r["likelihood"] - 1] += 1
    fig, ax = plt.subplots(figsize=(6, 5))
    # Background colour bands (green -> amber -> red) by L x I score.
    score = np.array([[(c + 1) * (5 - row) for c in range(5)] for row in range(5)])
    ax.imshow(score, cmap="RdYlGn_r", aspect="auto", alpha=0.85)
    for row in range(5):
        for col in range(5):
            n = grid[row, col]
            if n:
                ax.text(col, row, str(n), ha="center", va="center",
                        fontsize=11, fontweight="bold")
    ax.set_xticks(range(5)); ax.set_xticklabels([1, 2, 3, 4, 5])
    ax.set_yticks(range(5)); ax.set_yticklabels([5, 4, 3, 2, 1])
    ax.set_xlabel("Likelihood"); ax.set_ylabel("Impact")
    ax.set_title("Inherent risk heat map (count of risks)")
    fig.tight_layout()
    fig.savefig(OUT / "heatmap.png", dpi=130)
    plt.close(fig)


def residual_by_category(df: pd.DataFrame) -> pd.DataFrame:
    g = df.groupby("category")[["inherent_score", "residual_score"]].mean().round(1)
    g = g.sort_values("residual_score", ascending=False)
    fig, ax = plt.subplots(figsize=(8, 4.5))
    x = np.arange(len(g))
    ax.bar(x - 0.2, g["inherent_score"], 0.4, label="Inherent", color="#a6a6a6")
    ax.bar(x + 0.2, g["residual_score"], 0.4, label="Residual", color="#c00000")
    ax.set_xticks(x); ax.set_xticklabels(g.index, rotation=25, ha="right", fontsize=8)
    ax.set_ylabel("Avg risk score"); ax.set_title("Inherent vs residual risk by category")
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT / "residual_by_category.png", dpi=130)
    plt.close(fig)
    return g


def main() -> None:
    OUT.mkdir(exist_ok=True)
    df = load()
    heatmap(df)
    cat = residual_by_category(df)

    eff = (df["control_effectiveness"].value_counts(normalize=True) * 100).round(1)
    high = df[df["residual_score"] >= HIGH_RESIDUAL_THRESHOLD] \
        .sort_values("residual_score", ascending=False)
    overdue = df[df["review_status"] == "Overdue"]
    weak_high = df[(df["control_effectiveness"] == "Weak") &
                   (df["inherent_score"] >= HIGH_RESIDUAL_THRESHOLD)]

    md = []
    md.append("# Governance & Risk Report — Northwind Retail Group (synthetic)\n")
    md.append("> Fictional company. Data generated by `generate_data.py`. "
              "Risk scoring uses a standard 5x5 likelihood x impact model.\n")
    md.append("## Risk profile\n")
    md.append(f"- Risks on the register: **{len(df)}**")
    md.append(f"- High/extreme residual risks (score ≥ {HIGH_RESIDUAL_THRESHOLD}): "
              f"**{len(high)}**")
    md.append(f"- Reviews overdue (>12 months): **{len(overdue)}**\n")
    md.append("## Control effectiveness\n")
    for k, v in eff.items():
        md.append(f"- {k}: {v}%")
    md.append("")
    md.append("## Priority exceptions for the audit committee\n")
    md.append("**Weak controls over high inherent risks** (treat first):\n")
    if len(weak_high):
        md.append(weak_high[["risk_id", "category", "risk_title",
                             "inherent_score", "control_effectiveness"]]
                  .to_markdown(index=False))
    else:
        md.append("_None this cycle._")
    md.append("\n**Top residual risks:**\n")
    md.append(high.head(8)[["risk_id", "category", "risk_title",
                            "residual_score", "owner"]].to_markdown(index=False))
    md.append("\n## Inherent vs residual by category\n")
    md.append(cat.to_markdown())
    (OUT / "governance_report.md").write_text("\n".join(md))

    print(f"Risks: {len(df)} | High residual: {len(high)} | Overdue reviews: {len(overdue)}")
    print("Control effectiveness mix:\n", eff.to_string())
    print("Wrote outputs/heatmap.png, residual_by_category.png, governance_report.md")


if __name__ == "__main__":
    main()
